name: sakeny
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#-----------------------PACKAGES-----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl:
  flutter_native_splash:
  smooth_page_indicator:
  device_preview:
  flutter_screenutil:
  animated_custom_dropdown:

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  get_it:
  flutter_bloc:

  # Product Specific Packages


#-----------------------DEV DEPENDENCIES-----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


#-----------------------RESOURCES-----------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/

#-----------------------FONTS-----------------------#
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf